@hostname=127.0.0.1
@port=8000
@host={{hostname}}:{{port}}

GET http://{{host}}/api/health
Accept: application/json


###
POST http://{{host}}/api/short-code
Accept: application/json
Content-Type: application/json
Connection: keep-alive

{
  "short_url": "https://www.google.com"
}

###

GET http://{{host}}/code
