version: '3.8'
services:
  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis-cache:/data
      - ./redis.conf:/etc/redis/redis.conf

volumes:
  cache:
    driver: local

networks:
  infra-net:
    name: url-short-infra-net
    driver: bridge
